#!/bin/python3
 
x = float(input ("Please provide a number: "))
o = input("Provide an operator: ")
y = float(input ("Please provide another number: "))

if o == '+':
	print(x+y)
elif o == '-':
	print(x-y)
elif o == '/':
	print(x/y)
elif o == '*':
	print(x*y)
elif o == '**' or o == '^':
	print(x**y)
else:
	print("Cannot compute, Please run again")
